#Goal
float64 goal_position_x
float64 goal_position_y
float64 goal_position_theta
---
#Result
float64 final_position_x
float64 final_position_y
float64 final_position_theta
string message
---
#Feedback
float64 current_position_x
float64 current_position_y
float64 current_position_theta